/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ComputeMarket {
  export type JobDataStruct = {
    nodeId: BytesLike;
    requester: AddressLike;
    depositMinor: BigNumberish;
    estimatedHours: BigNumberish;
    startedAt: BigNumberish;
    endedAt: BigNumberish;
    status: BigNumberish;
    resultHash: BytesLike;
  };

  export type JobDataStructOutput = [
    nodeId: string,
    requester: string,
    depositMinor: bigint,
    estimatedHours: bigint,
    startedAt: bigint,
    endedAt: bigint,
    status: bigint,
    resultHash: string
  ] & {
    nodeId: string;
    requester: string;
    depositMinor: bigint;
    estimatedHours: bigint;
    startedAt: bigint;
    endedAt: bigint;
    status: bigint;
    resultHash: string;
  };

  export type NodeDataStruct = {
    venueOwner: AddressLike;
    pricePerHourMinor: BigNumberish;
    minBookingHours: BigNumberish;
    maxBookingHours: BigNumberish;
    active: boolean;
  };

  export type NodeDataStructOutput = [
    venueOwner: string,
    pricePerHourMinor: bigint,
    minBookingHours: bigint,
    maxBookingHours: bigint,
    active: boolean
  ] & {
    venueOwner: string;
    pricePerHourMinor: bigint;
    minBookingHours: bigint;
    maxBookingHours: bigint;
    active: boolean;
  };
}

export interface ComputeMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "PLATFORM_FEE_BPS"
      | "activateNode"
      | "assignJob"
      | "cancelJob"
      | "completeJob"
      | "deactivateNode"
      | "failJob"
      | "getJob"
      | "getNode"
      | "getNodeCount"
      | "jobs"
      | "nextJobId"
      | "nodeIds"
      | "nodes"
      | "operator"
      | "owner"
      | "platformFeeRecipient"
      | "registerNode"
      | "renounceOwnership"
      | "setOperator"
      | "setPlatformFeeRecipient"
      | "startJob"
      | "submitJob"
      | "token"
      | "transferOwnership"
      | "updateNode"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobAssigned"
      | "JobCancelled"
      | "JobCompleted"
      | "JobFailed"
      | "JobStarted"
      | "JobSubmitted"
      | "NodeActivated"
      | "NodeDeactivated"
      | "NodeRegistered"
      | "NodeUpdated"
      | "OperatorUpdated"
      | "OwnershipTransferred"
      | "PlatformFeeRecipientUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateNode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeJob",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateNode",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "failJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getNode", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getNodeCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nodeIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nodes", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerNode",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitJob",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateNode",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assignJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "failJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNodeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nodeIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateNode", data: BytesLike): Result;
}

export namespace JobAssignedEvent {
  export type InputTuple = [jobId: BigNumberish];
  export type OutputTuple = [jobId: bigint];
  export interface OutputObject {
    jobId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCancelledEvent {
  export type InputTuple = [jobId: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [jobId: bigint, refundAmount: bigint];
  export interface OutputObject {
    jobId: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    resultHash: BytesLike,
    venueAmount: BigNumberish,
    platformAmount: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    resultHash: string,
    venueAmount: bigint,
    platformAmount: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    resultHash: string;
    venueAmount: bigint;
    platformAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFailedEvent {
  export type InputTuple = [jobId: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [jobId: bigint, refundAmount: bigint];
  export interface OutputObject {
    jobId: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobStartedEvent {
  export type InputTuple = [jobId: BigNumberish, startedAt: BigNumberish];
  export type OutputTuple = [jobId: bigint, startedAt: bigint];
  export interface OutputObject {
    jobId: bigint;
    startedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobSubmittedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    nodeId: BytesLike,
    requester: AddressLike,
    depositMinor: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    nodeId: string,
    requester: string,
    depositMinor: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    nodeId: string;
    requester: string;
    depositMinor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeActivatedEvent {
  export type InputTuple = [nodeId: BytesLike];
  export type OutputTuple = [nodeId: string];
  export interface OutputObject {
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeDeactivatedEvent {
  export type InputTuple = [nodeId: BytesLike];
  export type OutputTuple = [nodeId: string];
  export interface OutputObject {
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeRegisteredEvent {
  export type InputTuple = [
    nodeId: BytesLike,
    venueOwner: AddressLike,
    pricePerHourMinor: BigNumberish
  ];
  export type OutputTuple = [
    nodeId: string,
    venueOwner: string,
    pricePerHourMinor: bigint
  ];
  export interface OutputObject {
    nodeId: string;
    venueOwner: string;
    pricePerHourMinor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeUpdatedEvent {
  export type InputTuple = [nodeId: BytesLike];
  export type OutputTuple = [nodeId: string];
  export interface OutputObject {
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorUpdatedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeRecipientUpdatedEvent {
  export type InputTuple = [recipient: AddressLike];
  export type OutputTuple = [recipient: string];
  export interface OutputObject {
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComputeMarket extends BaseContract {
  connect(runner?: ContractRunner | null): ComputeMarket;
  waitForDeployment(): Promise<this>;

  interface: ComputeMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  activateNode: TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;

  assignJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  cancelJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  completeJob: TypedContractMethod<
    [jobId: BigNumberish, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;

  deactivateNode: TypedContractMethod<
    [nodeId: BytesLike],
    [void],
    "nonpayable"
  >;

  failJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [ComputeMarket.JobDataStructOutput],
    "view"
  >;

  getNode: TypedContractMethod<
    [nodeId: BytesLike],
    [ComputeMarket.NodeDataStructOutput],
    "view"
  >;

  getNodeCount: TypedContractMethod<[], [bigint], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, string] & {
        nodeId: string;
        requester: string;
        depositMinor: bigint;
        estimatedHours: bigint;
        startedAt: bigint;
        endedAt: bigint;
        status: bigint;
        resultHash: string;
      }
    ],
    "view"
  >;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  nodeIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  nodes: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        venueOwner: string;
        pricePerHourMinor: bigint;
        minBookingHours: bigint;
        maxBookingHours: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeRecipient: TypedContractMethod<[], [string], "view">;

  registerNode: TypedContractMethod<
    [
      nodeId: BytesLike,
      venueOwner: AddressLike,
      pricePerHourMinor: BigNumberish,
      minBookingHours: BigNumberish,
      maxBookingHours: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOperator: TypedContractMethod<
    [operator_: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFeeRecipient: TypedContractMethod<
    [recipient_: AddressLike],
    [void],
    "nonpayable"
  >;

  startJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  submitJob: TypedContractMethod<
    [nodeId: BytesLike, estimatedHours: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateNode: TypedContractMethod<
    [
      nodeId: BytesLike,
      pricePerHourMinor: BigNumberish,
      minBookingHours: BigNumberish,
      maxBookingHours: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activateNode"
  ): TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeJob"
  ): TypedContractMethod<
    [jobId: BigNumberish, resultHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateNode"
  ): TypedContractMethod<[nodeId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "failJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [ComputeMarket.JobDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNode"
  ): TypedContractMethod<
    [nodeId: BytesLike],
    [ComputeMarket.NodeDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNodeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, string] & {
        nodeId: string;
        requester: string;
        depositMinor: bigint;
        estimatedHours: bigint;
        startedAt: bigint;
        endedAt: bigint;
        status: bigint;
        resultHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nodeIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "nodes"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, boolean] & {
        venueOwner: string;
        pricePerHourMinor: bigint;
        minBookingHours: bigint;
        maxBookingHours: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerNode"
  ): TypedContractMethod<
    [
      nodeId: BytesLike,
      venueOwner: AddressLike,
      pricePerHourMinor: BigNumberish,
      minBookingHours: BigNumberish,
      maxBookingHours: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[operator_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFeeRecipient"
  ): TypedContractMethod<[recipient_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitJob"
  ): TypedContractMethod<
    [nodeId: BytesLike, estimatedHours: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateNode"
  ): TypedContractMethod<
    [
      nodeId: BytesLike,
      pricePerHourMinor: BigNumberish,
      minBookingHours: BigNumberish,
      maxBookingHours: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "JobAssigned"
  ): TypedContractEvent<
    JobAssignedEvent.InputTuple,
    JobAssignedEvent.OutputTuple,
    JobAssignedEvent.OutputObject
  >;
  getEvent(
    key: "JobCancelled"
  ): TypedContractEvent<
    JobCancelledEvent.InputTuple,
    JobCancelledEvent.OutputTuple,
    JobCancelledEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobFailed"
  ): TypedContractEvent<
    JobFailedEvent.InputTuple,
    JobFailedEvent.OutputTuple,
    JobFailedEvent.OutputObject
  >;
  getEvent(
    key: "JobStarted"
  ): TypedContractEvent<
    JobStartedEvent.InputTuple,
    JobStartedEvent.OutputTuple,
    JobStartedEvent.OutputObject
  >;
  getEvent(
    key: "JobSubmitted"
  ): TypedContractEvent<
    JobSubmittedEvent.InputTuple,
    JobSubmittedEvent.OutputTuple,
    JobSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "NodeActivated"
  ): TypedContractEvent<
    NodeActivatedEvent.InputTuple,
    NodeActivatedEvent.OutputTuple,
    NodeActivatedEvent.OutputObject
  >;
  getEvent(
    key: "NodeDeactivated"
  ): TypedContractEvent<
    NodeDeactivatedEvent.InputTuple,
    NodeDeactivatedEvent.OutputTuple,
    NodeDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "NodeRegistered"
  ): TypedContractEvent<
    NodeRegisteredEvent.InputTuple,
    NodeRegisteredEvent.OutputTuple,
    NodeRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NodeUpdated"
  ): TypedContractEvent<
    NodeUpdatedEvent.InputTuple,
    NodeUpdatedEvent.OutputTuple,
    NodeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorUpdated"
  ): TypedContractEvent<
    OperatorUpdatedEvent.InputTuple,
    OperatorUpdatedEvent.OutputTuple,
    OperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeRecipientUpdated"
  ): TypedContractEvent<
    PlatformFeeRecipientUpdatedEvent.InputTuple,
    PlatformFeeRecipientUpdatedEvent.OutputTuple,
    PlatformFeeRecipientUpdatedEvent.OutputObject
  >;

  filters: {
    "JobAssigned(uint256)": TypedContractEvent<
      JobAssignedEvent.InputTuple,
      JobAssignedEvent.OutputTuple,
      JobAssignedEvent.OutputObject
    >;
    JobAssigned: TypedContractEvent<
      JobAssignedEvent.InputTuple,
      JobAssignedEvent.OutputTuple,
      JobAssignedEvent.OutputObject
    >;

    "JobCancelled(uint256,uint256)": TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;
    JobCancelled: TypedContractEvent<
      JobCancelledEvent.InputTuple,
      JobCancelledEvent.OutputTuple,
      JobCancelledEvent.OutputObject
    >;

    "JobCompleted(uint256,bytes32,uint256,uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobFailed(uint256,uint256)": TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;
    JobFailed: TypedContractEvent<
      JobFailedEvent.InputTuple,
      JobFailedEvent.OutputTuple,
      JobFailedEvent.OutputObject
    >;

    "JobStarted(uint256,uint256)": TypedContractEvent<
      JobStartedEvent.InputTuple,
      JobStartedEvent.OutputTuple,
      JobStartedEvent.OutputObject
    >;
    JobStarted: TypedContractEvent<
      JobStartedEvent.InputTuple,
      JobStartedEvent.OutputTuple,
      JobStartedEvent.OutputObject
    >;

    "JobSubmitted(uint256,bytes32,address,uint256)": TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;
    JobSubmitted: TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;

    "NodeActivated(bytes32)": TypedContractEvent<
      NodeActivatedEvent.InputTuple,
      NodeActivatedEvent.OutputTuple,
      NodeActivatedEvent.OutputObject
    >;
    NodeActivated: TypedContractEvent<
      NodeActivatedEvent.InputTuple,
      NodeActivatedEvent.OutputTuple,
      NodeActivatedEvent.OutputObject
    >;

    "NodeDeactivated(bytes32)": TypedContractEvent<
      NodeDeactivatedEvent.InputTuple,
      NodeDeactivatedEvent.OutputTuple,
      NodeDeactivatedEvent.OutputObject
    >;
    NodeDeactivated: TypedContractEvent<
      NodeDeactivatedEvent.InputTuple,
      NodeDeactivatedEvent.OutputTuple,
      NodeDeactivatedEvent.OutputObject
    >;

    "NodeRegistered(bytes32,address,uint256)": TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;
    NodeRegistered: TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;

    "NodeUpdated(bytes32)": TypedContractEvent<
      NodeUpdatedEvent.InputTuple,
      NodeUpdatedEvent.OutputTuple,
      NodeUpdatedEvent.OutputObject
    >;
    NodeUpdated: TypedContractEvent<
      NodeUpdatedEvent.InputTuple,
      NodeUpdatedEvent.OutputTuple,
      NodeUpdatedEvent.OutputObject
    >;

    "OperatorUpdated(address)": TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;
    OperatorUpdated: TypedContractEvent<
      OperatorUpdatedEvent.InputTuple,
      OperatorUpdatedEvent.OutputTuple,
      OperatorUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeRecipientUpdated(address)": TypedContractEvent<
      PlatformFeeRecipientUpdatedEvent.InputTuple,
      PlatformFeeRecipientUpdatedEvent.OutputTuple,
      PlatformFeeRecipientUpdatedEvent.OutputObject
    >;
    PlatformFeeRecipientUpdated: TypedContractEvent<
      PlatformFeeRecipientUpdatedEvent.InputTuple,
      PlatformFeeRecipientUpdatedEvent.OutputTuple,
      PlatformFeeRecipientUpdatedEvent.OutputObject
    >;
  };
}
