/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { AccessPassNFT } from "./AccessPassNFT";
export type { ComputeMarket } from "./ComputeMarket";
export type { DepositVault } from "./DepositVault";
export type { MockERC20 } from "./MockERC20";
export type { MockERC20Config } from "./MockERC20Config";
export type { MockERC721 } from "./MockERC721";
export type { NodeStayComputeRight } from "./NodeStayComputeRight";
export type { NodeStayMachineRegistry } from "./NodeStayMachineRegistry";
export type { NodeStayMarketplace } from "./NodeStayMarketplace";
export type { NodeStayRevenueRight } from "./NodeStayRevenueRight";
export type { NodeStaySettlement } from "./NodeStaySettlement";
export type { NodeStayUsageRight } from "./NodeStayUsageRight";
