/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NodeStaySettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "captureDeposit"
      | "depositPayer"
      | "heldAmount"
      | "holdDeposit"
      | "operator"
      | "owner"
      | "paymentToken"
      | "platformTreasury"
      | "releaseDeposit"
      | "renounceOwnership"
      | "setOperator"
      | "setPlatformTreasury"
      | "settleCompute"
      | "settleUsage"
      | "token"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComputeSettled"
      | "DepositCaptured"
      | "DepositHeld"
      | "DepositReleased"
      | "OwnershipTransferred"
      | "UsageSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "captureDeposit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositPayer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "heldAmount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "holdDeposit",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseDeposit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleCompute",
    values: [
      BytesLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settleUsage",
    values: [
      BytesLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "captureDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositPayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "heldAmount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "holdDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleCompute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ComputeSettledEvent {
  export type InputTuple = [
    jobId: BytesLike,
    gross: BigNumberish,
    venueShare: BigNumberish,
    platformShare: BigNumberish,
    revenueShare: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    gross: bigint,
    venueShare: bigint,
    platformShare: bigint,
    revenueShare: bigint
  ];
  export interface OutputObject {
    jobId: string;
    gross: bigint;
    venueShare: bigint;
    platformShare: bigint;
    revenueShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositCapturedEvent {
  export type InputTuple = [referenceId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [referenceId: string, amount: bigint];
  export interface OutputObject {
    referenceId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositHeldEvent {
  export type InputTuple = [
    referenceId: BytesLike,
    payer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    referenceId: string,
    payer: string,
    amount: bigint
  ];
  export interface OutputObject {
    referenceId: string;
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositReleasedEvent {
  export type InputTuple = [referenceId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [referenceId: string, amount: bigint];
  export interface OutputObject {
    referenceId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsageSettledEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    gross: BigNumberish,
    venueShare: BigNumberish,
    platformShare: BigNumberish,
    revenueShare: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: string,
    gross: bigint,
    venueShare: bigint,
    platformShare: bigint,
    revenueShare: bigint
  ];
  export interface OutputObject {
    sessionId: string;
    gross: bigint;
    venueShare: bigint;
    platformShare: bigint;
    revenueShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NodeStaySettlement extends BaseContract {
  connect(runner?: ContractRunner | null): NodeStaySettlement;
  waitForDeployment(): Promise<this>;

  interface: NodeStaySettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  captureDeposit: TypedContractMethod<
    [referenceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositPayer: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  heldAmount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  holdDeposit: TypedContractMethod<
    [referenceId: BytesLike, payer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  releaseDeposit: TypedContractMethod<
    [referenceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOperator: TypedContractMethod<
    [operator_: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [treasury_: AddressLike],
    [void],
    "nonpayable"
  >;

  settleCompute: TypedContractMethod<
    [
      jobId: BytesLike,
      arg1: BytesLike,
      payer: AddressLike,
      venueTreasury: AddressLike,
      grossAmount: BigNumberish,
      platformFeeBps: BigNumberish,
      revenueFeeBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settleUsage: TypedContractMethod<
    [
      sessionId: BytesLike,
      arg1: BytesLike,
      payer: AddressLike,
      venueTreasury: AddressLike,
      grossAmount: BigNumberish,
      platformFeeBps: BigNumberish,
      revenueFeeBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "captureDeposit"
  ): TypedContractMethod<
    [referenceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositPayer"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "heldAmount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "holdDeposit"
  ): TypedContractMethod<
    [referenceId: BytesLike, payer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseDeposit"
  ): TypedContractMethod<
    [referenceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<[operator_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[treasury_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleCompute"
  ): TypedContractMethod<
    [
      jobId: BytesLike,
      arg1: BytesLike,
      payer: AddressLike,
      venueTreasury: AddressLike,
      grossAmount: BigNumberish,
      platformFeeBps: BigNumberish,
      revenueFeeBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleUsage"
  ): TypedContractMethod<
    [
      sessionId: BytesLike,
      arg1: BytesLike,
      payer: AddressLike,
      venueTreasury: AddressLike,
      grossAmount: BigNumberish,
      platformFeeBps: BigNumberish,
      revenueFeeBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ComputeSettled"
  ): TypedContractEvent<
    ComputeSettledEvent.InputTuple,
    ComputeSettledEvent.OutputTuple,
    ComputeSettledEvent.OutputObject
  >;
  getEvent(
    key: "DepositCaptured"
  ): TypedContractEvent<
    DepositCapturedEvent.InputTuple,
    DepositCapturedEvent.OutputTuple,
    DepositCapturedEvent.OutputObject
  >;
  getEvent(
    key: "DepositHeld"
  ): TypedContractEvent<
    DepositHeldEvent.InputTuple,
    DepositHeldEvent.OutputTuple,
    DepositHeldEvent.OutputObject
  >;
  getEvent(
    key: "DepositReleased"
  ): TypedContractEvent<
    DepositReleasedEvent.InputTuple,
    DepositReleasedEvent.OutputTuple,
    DepositReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UsageSettled"
  ): TypedContractEvent<
    UsageSettledEvent.InputTuple,
    UsageSettledEvent.OutputTuple,
    UsageSettledEvent.OutputObject
  >;

  filters: {
    "ComputeSettled(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ComputeSettledEvent.InputTuple,
      ComputeSettledEvent.OutputTuple,
      ComputeSettledEvent.OutputObject
    >;
    ComputeSettled: TypedContractEvent<
      ComputeSettledEvent.InputTuple,
      ComputeSettledEvent.OutputTuple,
      ComputeSettledEvent.OutputObject
    >;

    "DepositCaptured(bytes32,uint256)": TypedContractEvent<
      DepositCapturedEvent.InputTuple,
      DepositCapturedEvent.OutputTuple,
      DepositCapturedEvent.OutputObject
    >;
    DepositCaptured: TypedContractEvent<
      DepositCapturedEvent.InputTuple,
      DepositCapturedEvent.OutputTuple,
      DepositCapturedEvent.OutputObject
    >;

    "DepositHeld(bytes32,address,uint256)": TypedContractEvent<
      DepositHeldEvent.InputTuple,
      DepositHeldEvent.OutputTuple,
      DepositHeldEvent.OutputObject
    >;
    DepositHeld: TypedContractEvent<
      DepositHeldEvent.InputTuple,
      DepositHeldEvent.OutputTuple,
      DepositHeldEvent.OutputObject
    >;

    "DepositReleased(bytes32,uint256)": TypedContractEvent<
      DepositReleasedEvent.InputTuple,
      DepositReleasedEvent.OutputTuple,
      DepositReleasedEvent.OutputObject
    >;
    DepositReleased: TypedContractEvent<
      DepositReleasedEvent.InputTuple,
      DepositReleasedEvent.OutputTuple,
      DepositReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UsageSettled(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UsageSettledEvent.InputTuple,
      UsageSettledEvent.OutputTuple,
      UsageSettledEvent.OutputObject
    >;
    UsageSettled: TypedContractEvent<
      UsageSettledEvent.InputTuple,
      UsageSettledEvent.OutputTuple,
      UsageSettledEvent.OutputObject
    >;
  };
}
