/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INodeStayMachineRegistry } from "./INodeStayMachineRegistry";
export type { INodeStaySettlement } from "./INodeStaySettlement";
export type { INodeStayUsageRight } from "./INodeStayUsageRight";
