/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface INodeStaySettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "captureDeposit"
      | "holdDeposit"
      | "paymentToken"
      | "releaseDeposit"
      | "settleCompute"
      | "settleUsage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComputeSettled"
      | "DepositCaptured"
      | "DepositHeld"
      | "DepositReleased"
      | "UsageSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "captureDeposit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "holdDeposit",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseDeposit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleCompute",
    values: [
      BytesLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "settleUsage",
    values: [
      BytesLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "captureDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holdDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleCompute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleUsage",
    data: BytesLike
  ): Result;
}

export namespace ComputeSettledEvent {
  export type InputTuple = [
    jobId: BytesLike,
    gross: BigNumberish,
    venueShare: BigNumberish,
    platformShare: BigNumberish,
    revenueShare: BigNumberish
  ];
  export type OutputTuple = [
    jobId: string,
    gross: bigint,
    venueShare: bigint,
    platformShare: bigint,
    revenueShare: bigint
  ];
  export interface OutputObject {
    jobId: string;
    gross: bigint;
    venueShare: bigint;
    platformShare: bigint;
    revenueShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositCapturedEvent {
  export type InputTuple = [referenceId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [referenceId: string, amount: bigint];
  export interface OutputObject {
    referenceId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositHeldEvent {
  export type InputTuple = [
    referenceId: BytesLike,
    payer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    referenceId: string,
    payer: string,
    amount: bigint
  ];
  export interface OutputObject {
    referenceId: string;
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositReleasedEvent {
  export type InputTuple = [referenceId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [referenceId: string, amount: bigint];
  export interface OutputObject {
    referenceId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsageSettledEvent {
  export type InputTuple = [
    sessionId: BytesLike,
    gross: BigNumberish,
    venueShare: BigNumberish,
    platformShare: BigNumberish,
    revenueShare: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: string,
    gross: bigint,
    venueShare: bigint,
    platformShare: bigint,
    revenueShare: bigint
  ];
  export interface OutputObject {
    sessionId: string;
    gross: bigint;
    venueShare: bigint;
    platformShare: bigint;
    revenueShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface INodeStaySettlement extends BaseContract {
  connect(runner?: ContractRunner | null): INodeStaySettlement;
  waitForDeployment(): Promise<this>;

  interface: INodeStaySettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  captureDeposit: TypedContractMethod<
    [referenceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  holdDeposit: TypedContractMethod<
    [referenceId: BytesLike, payer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  paymentToken: TypedContractMethod<[], [string], "view">;

  releaseDeposit: TypedContractMethod<
    [referenceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  settleCompute: TypedContractMethod<
    [
      jobId: BytesLike,
      machineId: BytesLike,
      payer: AddressLike,
      venueTreasury: AddressLike,
      grossAmount: BigNumberish,
      platformFeeBps: BigNumberish,
      revenueFeeBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settleUsage: TypedContractMethod<
    [
      sessionId: BytesLike,
      machineId: BytesLike,
      payer: AddressLike,
      venueTreasury: AddressLike,
      grossAmount: BigNumberish,
      platformFeeBps: BigNumberish,
      revenueFeeBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "captureDeposit"
  ): TypedContractMethod<
    [referenceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "holdDeposit"
  ): TypedContractMethod<
    [referenceId: BytesLike, payer: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseDeposit"
  ): TypedContractMethod<
    [referenceId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleCompute"
  ): TypedContractMethod<
    [
      jobId: BytesLike,
      machineId: BytesLike,
      payer: AddressLike,
      venueTreasury: AddressLike,
      grossAmount: BigNumberish,
      platformFeeBps: BigNumberish,
      revenueFeeBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleUsage"
  ): TypedContractMethod<
    [
      sessionId: BytesLike,
      machineId: BytesLike,
      payer: AddressLike,
      venueTreasury: AddressLike,
      grossAmount: BigNumberish,
      platformFeeBps: BigNumberish,
      revenueFeeBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComputeSettled"
  ): TypedContractEvent<
    ComputeSettledEvent.InputTuple,
    ComputeSettledEvent.OutputTuple,
    ComputeSettledEvent.OutputObject
  >;
  getEvent(
    key: "DepositCaptured"
  ): TypedContractEvent<
    DepositCapturedEvent.InputTuple,
    DepositCapturedEvent.OutputTuple,
    DepositCapturedEvent.OutputObject
  >;
  getEvent(
    key: "DepositHeld"
  ): TypedContractEvent<
    DepositHeldEvent.InputTuple,
    DepositHeldEvent.OutputTuple,
    DepositHeldEvent.OutputObject
  >;
  getEvent(
    key: "DepositReleased"
  ): TypedContractEvent<
    DepositReleasedEvent.InputTuple,
    DepositReleasedEvent.OutputTuple,
    DepositReleasedEvent.OutputObject
  >;
  getEvent(
    key: "UsageSettled"
  ): TypedContractEvent<
    UsageSettledEvent.InputTuple,
    UsageSettledEvent.OutputTuple,
    UsageSettledEvent.OutputObject
  >;

  filters: {
    "ComputeSettled(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ComputeSettledEvent.InputTuple,
      ComputeSettledEvent.OutputTuple,
      ComputeSettledEvent.OutputObject
    >;
    ComputeSettled: TypedContractEvent<
      ComputeSettledEvent.InputTuple,
      ComputeSettledEvent.OutputTuple,
      ComputeSettledEvent.OutputObject
    >;

    "DepositCaptured(bytes32,uint256)": TypedContractEvent<
      DepositCapturedEvent.InputTuple,
      DepositCapturedEvent.OutputTuple,
      DepositCapturedEvent.OutputObject
    >;
    DepositCaptured: TypedContractEvent<
      DepositCapturedEvent.InputTuple,
      DepositCapturedEvent.OutputTuple,
      DepositCapturedEvent.OutputObject
    >;

    "DepositHeld(bytes32,address,uint256)": TypedContractEvent<
      DepositHeldEvent.InputTuple,
      DepositHeldEvent.OutputTuple,
      DepositHeldEvent.OutputObject
    >;
    DepositHeld: TypedContractEvent<
      DepositHeldEvent.InputTuple,
      DepositHeldEvent.OutputTuple,
      DepositHeldEvent.OutputObject
    >;

    "DepositReleased(bytes32,uint256)": TypedContractEvent<
      DepositReleasedEvent.InputTuple,
      DepositReleasedEvent.OutputTuple,
      DepositReleasedEvent.OutputObject
    >;
    DepositReleased: TypedContractEvent<
      DepositReleasedEvent.InputTuple,
      DepositReleasedEvent.OutputTuple,
      DepositReleasedEvent.OutputObject
    >;

    "UsageSettled(bytes32,uint256,uint256,uint256,uint256)": TypedContractEvent<
      UsageSettledEvent.InputTuple,
      UsageSettledEvent.OutputTuple,
      UsageSettledEvent.OutputObject
    >;
    UsageSettled: TypedContractEvent<
      UsageSettledEvent.InputTuple,
      UsageSettledEvent.OutputTuple,
      UsageSettledEvent.OutputObject
    >;
  };
}
