/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INodeStaySettlement,
  INodeStaySettlementInterface,
} from "../../../contracts/interfaces/INodeStaySettlement";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "jobId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "gross",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "venueShare",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "platformShare",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "revenueShare",
        type: "uint256",
      },
    ],
    name: "ComputeSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "referenceId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DepositCaptured",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "referenceId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DepositHeld",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "referenceId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DepositReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "sessionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "gross",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "venueShare",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "platformShare",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "revenueShare",
        type: "uint256",
      },
    ],
    name: "UsageSettled",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "referenceId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "captureDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "referenceId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "holdDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paymentToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "referenceId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "releaseDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "jobId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "machineId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "venueTreasury",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "grossAmount",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "platformFeeBps",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "revenueFeeBps",
        type: "uint16",
      },
    ],
    name: "settleCompute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sessionId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "machineId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        internalType: "address",
        name: "venueTreasury",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "grossAmount",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "platformFeeBps",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "revenueFeeBps",
        type: "uint16",
      },
    ],
    name: "settleUsage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INodeStaySettlement__factory {
  static readonly abi = _abi;
  static createInterface(): INodeStaySettlementInterface {
    return new Interface(_abi) as INodeStaySettlementInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INodeStaySettlement {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as INodeStaySettlement;
  }
}
